'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { Property, Transaction, RawTransaction } from '@/lib/types';
import {
  matchCategory,
  matchProperty,
  assignAllProperties,
  buildPropertySummaries,
  ALL_CATEGORIES,
  SCHEDULE_E_LINES,
} from '@/lib/categories';
import {
  getProperties,
  saveProperties,
  getLearnedRules,
  saveLearnedRules,
  getReports,
  saveReport,
  deleteReport,
  clearAllData,
  SavedReport,
} from '@/lib/storage';
import { exportExcel, exportCSV } from '@/lib/export';

function genId() {
  return Math.random().toString(36).slice(2, 10);
}

function fmt(n: number) {
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

const CAT_COLORS: Record<string, string> = {
  '3': 'bg-emerald-100 text-emerald-800',
  '5': 'bg-purple-100 text-purple-800',
  '7': 'bg-sky-100 text-sky-800',
  '9': 'bg-indigo-100 text-indigo-800',
  '10': 'bg-violet-100 text-violet-800',
  '11': 'bg-cyan-100 text-cyan-800',
  '12': 'bg-rose-100 text-rose-800',
  '14': 'bg-orange-100 text-orange-800',
  '15': 'bg-amber-100 text-amber-800',
  '16': 'bg-red-100 text-red-800',
  '17': 'bg-blue-100 text-blue-800',
  '19': 'bg-gray-100 text-gray-700',
};

function getCatLine(category: string): string {
  const m = category.match(/^Line (\d+)/);
  return m ? m[1] : '19';
}

// ── Schedule E Print ────────────────────────────────────────────────────────

function printScheduleE(
  categoryTotals: Record<string, number>,
  totalIncome: number,
  totalExpenses: number,
  filename: string,
  properties: Property[]
) {
  const rows = SCHEDULE_E_LINES.filter(([num]) => categoryTotals[num])
    .map(
      ([num, name]) =>
        `<tr>
          <td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;color:#6b7280;font-family:monospace">${num}</td>
          <td style="padding:6px 12px;border-bottom:1px solid #e5e7eb">${name}</td>
          <td style="padding:6px 12px;border-bottom:1px solid #e5e7eb;text-align:right;font-family:monospace;color:${categoryTotals[num] >= 0 ? '#059669' : '#dc2626'}">${fmt(categoryTotals[num])}</td>
        </tr>`
    )
    .join('');

  const propList = properties.length
    ? `<p style="color:#6b7280;font-size:12px;margin-top:4px">Properties: ${properties.map((p) => p.address).join(' | ')}</p>`
    : '';

  const html = `<!DOCTYPE html>
<html><head><title>Schedule E - ${filename}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 40px auto; color: #111; }
  @media print { body { margin: 20px; } }
  h1 { font-size: 22px; margin-bottom: 2px; }
  h2 { font-size: 14px; color: #6b7280; font-weight: normal; margin-top: 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px; }
  thead th { padding: 8px 12px; text-align: left; font-size: 12px; color: #6b7280; border-bottom: 2px solid #d1d5db; }
  thead th:last-child { text-align: right; }
  .net { font-weight: bold; font-size: 16px; border-top: 2px solid #111; }
  .net td { padding: 12px; }
</style></head><body>
<h1>IRS Schedule E — Supplemental Income and Loss</h1>
<h2>${filename.replace(/\.pdf$/i, '')}</h2>
${propList}
<table>
  <thead><tr><th>Line</th><th>Category</th><th style="text-align:right">Amount</th></tr></thead>
  <tbody>
    ${rows}
    <tr class="net">
      <td></td>
      <td>Net Rental Income (Line 21)</td>
      <td style="text-align:right;font-family:monospace;color:${totalIncome + totalExpenses >= 0 ? '#059669' : '#dc2626'}">${fmt(totalIncome + totalExpenses)}</td>
    </tr>
  </tbody>
</table>
<p style="margin-top:40px;font-size:11px;color:#9ca3af">Generated by ScheduleEHelper &middot; ${new Date().toLocaleDateString()}</p>
</body></html>`;

  const w = window.open('', '_blank');
  if (w) {
    w.document.write(html);
    w.document.close();
    w.setTimeout(() => w.print(), 300);
  }
}

// ── Main Component ──────────────────────────────────────────────────────────

export default function ScheduleETool() {
  const [properties, setPropertiesState] = useState<Property[]>([]);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [view, setView] = useState<'upload' | 'review'>('upload');
  const [loading, setLoading] = useState(false);
  const [filename, setFilename] = useState('');
  const [showProps, setShowProps] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const [flash, setFlash] = useState('');
  const [visibleCount, setVisibleCount] = useState(0);
  const [showSummary, setShowSummary] = useState(false);
  const [showMenu, setShowMenu] = useState(false);
  const fileRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const saved = getProperties();
    setPropertiesState(saved);
  }, []);

  useEffect(() => {
    if (view === 'review' && visibleCount < transactions.length) {
      const timer = setTimeout(() => {
        setVisibleCount((c) => Math.min(c + 3, transactions.length));
      }, 30);
      return () => clearTimeout(timer);
    }
  }, [view, visibleCount, transactions.length]);

  const showFlash = useCallback((msg: string) => {
    setFlash(msg);
    setTimeout(() => setFlash(''), 6000);
  }, []);

  // ── Properties ────────────────────────────────────────────────────────────

  const updateProperties = (props: Property[]) => {
    setPropertiesState(props);
    saveProperties(props);
  };

  const addProperty = () => {
    updateProperties([
      ...properties,
      { id: genId(), address: '', type: 'Multi-Family', units: 2 },
    ]);
  };

  const removeProperty = (id: string) => {
    updateProperties(properties.filter((p) => p.id !== id));
  };

  const updateProp = (id: string, field: keyof Property, value: string | number) => {
    updateProperties(
      properties.map((p) => (p.id === id ? { ...p, [field]: value } : p))
    );
  };

  // ── Upload ────────────────────────────────────────────────────────────────

  const handleFile = async (file: File) => {
    if (!file.name.toLowerCase().endsWith('.pdf')) {
      showFlash('Please upload a PDF file.');
      return;
    }

    setLoading(true);
    setTransactions([]);
    setVisibleCount(0);
    setShowSummary(false);

    try {
      const formData = new FormData();
      formData.append('file', file);
      const res = await fetch('/api/parse', { method: 'POST', body: formData });
      const json = await res.json();

      if (!res.ok) {
        showFlash(json.error || 'Failed to parse PDF.');
        setLoading(false);
        return;
      }

      const raw: RawTransaction[] = json.transactions;
      const rules = getLearnedRules();
      const addrs = properties.map((p) => p.address);

      let categorized: Transaction[] = raw.map((txn, i) => {
        const category =
          matchCategory(txn.description, rules) ||
          (txn.amount > 0 ? 'Line 3: Rents received' : 'Line 19: Other');
        const { property, confidence } = matchProperty(txn.description, addrs);
        return {
          ...txn,
          id: String(i),
          category,
          property: property || '',
          confidence: confidence || '',
          autoMatched: true,
        };
      });

      if (properties.length > 0) {
        categorized = assignAllProperties(categorized, properties);
      }

      setTransactions(categorized);
      setFilename(file.name);
      setView('review');

      const incomeCount = categorized.filter((t) => t.amount > 0).length;
      const expenseCount = categorized.filter((t) => t.amount < 0).length;
      showFlash(
        `Extracted ${raw.length} transactions: ${incomeCount} income, ${expenseCount} expenses`
      );
    } catch {
      showFlash('Error parsing PDF. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ── Edits ─────────────────────────────────────────────────────────────────

  const handleCategoryChange = (id: string, newCat: string) => {
    setTransactions((prev) =>
      prev.map((t) => {
        if (t.id === id) {
          const rules = getLearnedRules();
          rules[t.description.trim()] = newCat;
          saveLearnedRules(rules);
          return { ...t, category: newCat };
        }
        return t;
      })
    );
  };

  // ── Summaries & Export ────────────────────────────────────────────────────

  const summaries =
    transactions.length > 0 ? buildPropertySummaries(transactions, properties) : {};

  const categoryTotals: Record<string, number> = {};
  for (const txn of transactions) {
    const line = getCatLine(txn.category);
    categoryTotals[line] = (categoryTotals[line] || 0) + txn.amount;
  }

  const totalIncome = categoryTotals['3'] || 0;
  const totalExpenses = Object.entries(categoryTotals)
    .filter(([k]) => k !== '3')
    .reduce((s, [, v]) => s + v, 0);

  const handleExportExcel = async () => {
    await exportExcel(transactions, summaries, filename);
  };
  const handleExportCSV = () => exportCSV(transactions, summaries, filename);
  const handlePrintScheduleE = () =>
    printScheduleE(categoryTotals, totalIncome, totalExpenses, filename, properties);

  const handleSaveReport = () => {
    saveReport({
      id: genId(),
      label: filename.replace(/\.pdf$/i, ''),
      filename,
      transactions,
      savedAt: new Date().toISOString(),
    });
    showFlash('Report saved.');
  };

  const handleLoadReport = (report: SavedReport) => {
    setTransactions(report.transactions);
    setFilename(report.filename);
    setVisibleCount(report.transactions.length);
    setView('review');
  };

  // ── Annual consolidation ──────────────────────────────────────────────────

  const handleConsolidate = (reportIds: string[]) => {
    const reports = getReports().filter((r) => reportIds.includes(r.id));
    if (reports.length === 0) return;

    const allTxns: Transaction[] = [];
    let counter = 0;
    for (const report of reports) {
      for (const txn of report.transactions) {
        allTxns.push({ ...txn, id: `c_${counter++}` });
      }
    }

    setTransactions(allTxns);
    setFilename(`Annual_${reports.length}_statements`);
    setVisibleCount(allTxns.length);
    setView('review');
    showFlash(
      `Consolidated ${reports.length} reports: ${allTxns.length} total transactions`
    );
  };

  // ── Clear data ────────────────────────────────────────────────────────────

  const handleClearData = () => {
    if (
      window.confirm(
        'This will delete all saved properties, rules, and reports. Are you sure?'
      )
    ) {
      clearAllData();
      setPropertiesState([]);
      setTransactions([]);
      setView('upload');
      setShowMenu(false);
      showFlash('All data cleared.');
    }
  };

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-gray-950 text-gray-100">
      {/* Header */}
      <header className="bg-gray-900 border-b border-gray-800 sticky top-0 z-30">
        <div className="max-w-4xl mx-auto px-3 sm:px-6 py-3 flex items-center justify-between gap-2">
          <div className="min-w-0">
            <h1 className="text-base sm:text-lg font-bold text-white truncate">
              ScheduleEHelper
            </h1>
            <p className="text-[10px] sm:text-xs text-gray-500 hidden sm:block">
              Upload bank statement &rarr; categorized transactions &rarr; Schedule E
            </p>
          </div>
          <div className="flex gap-1.5 sm:gap-2 shrink-0">
            {properties.length > 0 && (
              <button
                onClick={() => setShowProps(!showProps)}
                className="text-[11px] sm:text-xs px-2 sm:px-3 py-1.5 rounded-lg border border-gray-700 text-gray-400 hover:text-white hover:border-gray-500 transition-colors"
              >
                Properties ({properties.length})
              </button>
            )}
            {view === 'review' && (
              <button
                onClick={() => {
                  setView('upload');
                  setShowSummary(false);
                }}
                className="text-[11px] sm:text-xs px-2 sm:px-3 py-1.5 rounded-lg border border-gray-700 text-gray-400 hover:text-white hover:border-gray-500 transition-colors"
              >
                &larr; New
              </button>
            )}
            {/* Menu */}
            <div className="relative">
              <button
                onClick={() => setShowMenu(!showMenu)}
                className="text-[11px] sm:text-xs px-2 py-1.5 rounded-lg border border-gray-700 text-gray-400 hover:text-white hover:border-gray-500 transition-colors"
              >
                &#8942;
              </button>
              {showMenu && (
                <div className="absolute right-0 mt-1 w-44 bg-gray-800 border border-gray-700 rounded-lg shadow-xl z-40 py-1">
                  <button
                    onClick={() => {
                      setShowProps(true);
                      setShowMenu(false);
                    }}
                    className="w-full text-left px-3 py-2 text-xs text-gray-300 hover:bg-gray-700"
                  >
                    Manage Properties
                  </button>
                  <button
                    onClick={() => {
                      handleClearData();
                    }}
                    className="w-full text-left px-3 py-2 text-xs text-red-400 hover:bg-gray-700"
                  >
                    Clear All Data
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* Flash */}
      {flash && (
        <div className="max-w-4xl mx-auto px-3 sm:px-6 mt-3">
          <div className="bg-emerald-900/50 border border-emerald-700 text-emerald-300 px-3 sm:px-4 py-2 rounded-lg text-xs sm:text-sm">
            {flash}
          </div>
        </div>
      )}

      {/* Property panel */}
      {showProps && (
        <div className="max-w-4xl mx-auto px-3 sm:px-6 mt-4">
          <div className="bg-gray-900 rounded-xl border border-gray-800 p-3 sm:p-4">
            <div className="flex items-center justify-between mb-3">
              <h2 className="font-semibold text-sm text-gray-300">
                Your Rental Properties
              </h2>
              <button
                onClick={addProperty}
                className="text-xs px-3 py-1 rounded-lg bg-emerald-600 text-white hover:bg-emerald-500"
              >
                + Add
              </button>
            </div>
            {properties.length === 0 ? (
              <p className="text-sm text-gray-600 py-4 text-center">
                No properties yet. Add your rentals to enable property-level
                reports.
              </p>
            ) : (
              <div className="space-y-2">
                {properties.map((p) => (
                  <div
                    key={p.id}
                    className="flex flex-col sm:flex-row gap-2 sm:items-center"
                  >
                    <input
                      className="flex-1 bg-gray-800 border border-gray-700 rounded-lg px-3 py-1.5 text-sm text-white placeholder-gray-600 focus:outline-none focus:border-emerald-500"
                      placeholder="Address"
                      value={p.address}
                      onChange={(e) => updateProp(p.id, 'address', e.target.value)}
                    />
                    <div className="flex gap-2 items-center">
                      <input
                        className="w-16 bg-gray-800 border border-gray-700 rounded-lg px-2 py-1.5 text-sm text-white text-center focus:outline-none focus:border-emerald-500"
                        type="number"
                        min={1}
                        placeholder="Units"
                        value={p.units}
                        onChange={(e) =>
                          updateProp(p.id, 'units', parseInt(e.target.value) || 1)
                        }
                      />
                      <button
                        onClick={() => removeProperty(p.id)}
                        className="text-gray-600 hover:text-red-400 px-1 text-lg"
                      >
                        &times;
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
            <div className="mt-3 flex justify-end">
              <button
                onClick={() => setShowProps(false)}
                className="text-xs px-3 py-1.5 rounded-lg border border-gray-700 text-gray-400 hover:text-white"
              >
                Done
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Close menu on outside click */}
      {showMenu && (
        <div
          className="fixed inset-0 z-20"
          onClick={() => setShowMenu(false)}
        />
      )}

      {/* Main */}
      <main className="max-w-4xl mx-auto px-3 sm:px-6 py-4 sm:py-6">
        {view === 'upload' ? (
          <>
            {/* Upload area */}
            <div
              className={`border-2 border-dashed rounded-xl p-10 sm:p-20 text-center transition-all cursor-pointer ${
                dragOver
                  ? 'border-emerald-500 bg-emerald-950/30'
                  : 'border-gray-700 bg-gray-900 hover:border-gray-600'
              }`}
              onDragOver={(e) => {
                e.preventDefault();
                setDragOver(true);
              }}
              onDragLeave={() => setDragOver(false)}
              onDrop={(e) => {
                e.preventDefault();
                setDragOver(false);
                if (e.dataTransfer.files[0]) handleFile(e.dataTransfer.files[0]);
              }}
              onClick={() => fileRef.current?.click()}
            >
              <input
                ref={fileRef}
                type="file"
                accept=".pdf"
                className="hidden"
                onChange={(e) => {
                  if (e.target.files?.[0]) handleFile(e.target.files[0]);
                }}
              />
              {loading ? (
                <div>
                  <div className="animate-spin h-10 w-10 border-4 border-emerald-500 border-t-transparent rounded-full mx-auto mb-4" />
                  <p className="text-gray-400 text-sm">
                    Extracting transactions...
                  </p>
                </div>
              ) : (
                <div>
                  <div className="text-4xl sm:text-5xl mb-4 opacity-30">
                    &#128196;
                  </div>
                  <p className="text-base sm:text-lg font-medium text-gray-300 mb-1">
                    Drop your bank statement PDF
                  </p>
                  <p className="text-xs sm:text-sm text-gray-600">
                    Supports KeyBank, Chase, Bank of America, Wells Fargo &amp;
                    more
                  </p>
                </div>
              )}
            </div>

            {/* Setup prompt */}
            {properties.length === 0 && (
              <button
                onClick={() => setShowProps(true)}
                className="mt-4 w-full text-left bg-gray-900 border border-gray-800 rounded-xl p-4 hover:border-gray-700 transition-colors"
              >
                <p className="text-sm font-medium text-gray-300">
                  Optional: Add your properties
                </p>
                <p className="text-xs text-gray-600 mt-1">
                  Enable per-property Schedule E breakdowns by adding your
                  rental addresses
                </p>
              </button>
            )}

            <SavedReportsSection
              onLoad={handleLoadReport}
              onConsolidate={handleConsolidate}
            />
          </>
        ) : (
          <>
            {/* ── Review View ──────────────────────────────────────────── */}

            {/* Top bar */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4">
              <div className="min-w-0">
                <h2 className="text-xs sm:text-sm font-mono text-gray-500 truncate">
                  {filename}
                </h2>
                <p className="text-[10px] sm:text-xs text-gray-600 mt-0.5">
                  {transactions.length} transactions &middot; Income:{' '}
                  <span className="text-emerald-400">{fmt(totalIncome)}</span>{' '}
                  &middot; Expenses:{' '}
                  <span className="text-red-400">{fmt(totalExpenses)}</span>
                </p>
              </div>
              <div className="flex flex-wrap gap-1.5 sm:gap-2 shrink-0">
                <button
                  onClick={handleSaveReport}
                  className="text-[11px] sm:text-xs px-2 sm:px-3 py-1.5 rounded-lg border border-gray-700 text-gray-400 hover:text-white transition-colors"
                >
                  Save
                </button>
                <button
                  onClick={handlePrintScheduleE}
                  className="text-[11px] sm:text-xs px-2 sm:px-3 py-1.5 rounded-lg border border-gray-700 text-gray-400 hover:text-white transition-colors"
                >
                  Print Schedule E
                </button>
                <button
                  onClick={handleExportCSV}
                  className="text-[11px] sm:text-xs px-2 sm:px-3 py-1.5 rounded-lg border border-gray-700 text-gray-400 hover:text-white transition-colors"
                >
                  CSV
                </button>
                <button
                  onClick={handleExportExcel}
                  className="text-[11px] sm:text-xs px-2 sm:px-3 py-1.5 rounded-lg bg-emerald-600 text-white hover:bg-emerald-500 transition-colors"
                >
                  Export Excel
                </button>
              </div>
            </div>

            {/* Transaction log */}
            <div className="space-y-1">
              {transactions.slice(0, visibleCount).map((txn, i) => {
                const lineNum = getCatLine(txn.category);
                const colorClass = CAT_COLORS[lineNum] || CAT_COLORS['19'];
                const isIncome = txn.amount > 0;

                return (
                  <div
                    key={txn.id}
                    className="bg-gray-900 border border-gray-800 rounded-lg px-3 sm:px-4 py-2.5 sm:py-3 hover:border-gray-700 transition-all animate-in"
                    style={{ animationDelay: `${i * 20}ms` }}
                  >
                    <div className="flex items-start justify-between gap-2 sm:gap-4">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 sm:gap-3">
                          <span className="text-[10px] sm:text-xs font-mono text-gray-500 shrink-0">
                            {txn.date}
                          </span>
                          <span
                            className="text-xs sm:text-sm text-gray-200 truncate"
                            title={txn.description}
                          >
                            {txn.description}
                          </span>
                        </div>
                        <div className="flex items-center gap-2 mt-1 sm:mt-1.5 ml-0 sm:ml-[4.5rem]">
                          <span className="text-gray-600 text-xs hidden sm:inline">
                            &rarr;
                          </span>
                          <select
                            value={txn.category}
                            onChange={(e) =>
                              handleCategoryChange(txn.id, e.target.value)
                            }
                            className={`text-[10px] sm:text-xs font-medium px-1.5 sm:px-2 py-0.5 rounded-full border-0 cursor-pointer ${colorClass} focus:outline-none focus:ring-2 focus:ring-emerald-500`}
                          >
                            {ALL_CATEGORIES.map((cat) => (
                              <option key={cat} value={cat}>
                                {cat}
                              </option>
                            ))}
                          </select>
                          {txn.property && (
                            <span className="text-[10px] sm:text-xs text-gray-600 truncate hidden sm:inline">
                              @ {txn.property}
                            </span>
                          )}
                        </div>
                      </div>
                      <span
                        className={`text-xs sm:text-sm font-mono font-semibold tabular-nums shrink-0 ${
                          isIncome ? 'text-emerald-400' : 'text-red-400'
                        }`}
                      >
                        {isIncome ? '+' : ''}
                        {fmt(txn.amount)}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>

            {visibleCount < transactions.length && (
              <div className="text-center py-4">
                <div className="animate-pulse text-gray-600 text-sm">
                  Loading transactions... ({visibleCount}/{transactions.length})
                </div>
              </div>
            )}

            {/* Schedule E Summary */}
            {visibleCount >= transactions.length && transactions.length > 0 && (
              <div className="mt-6">
                <button
                  onClick={() => setShowSummary(!showSummary)}
                  className="w-full text-left bg-gray-900 border border-gray-800 rounded-xl p-4 hover:border-gray-700 transition-colors"
                >
                  <div className="flex items-center justify-between">
                    <div>
                      <h3 className="text-sm font-semibold text-white">
                        Schedule E Summary
                      </h3>
                      <p className="text-xs text-gray-500 mt-0.5">
                        Net Income:{' '}
                        <span
                          className={
                            totalIncome + totalExpenses >= 0
                              ? 'text-emerald-400'
                              : 'text-red-400'
                          }
                        >
                          {fmt(totalIncome + totalExpenses)}
                        </span>
                      </p>
                    </div>
                    <span className="text-gray-600">
                      {showSummary ? '\u25B2' : '\u25BC'}
                    </span>
                  </div>
                </button>

                {showSummary && (
                  <div className="mt-2 bg-gray-900 border border-gray-800 rounded-xl overflow-x-auto">
                    <table className="w-full text-xs sm:text-sm">
                      <thead>
                        <tr className="border-b border-gray-800">
                          <th className="px-3 sm:px-4 py-2 text-left text-xs text-gray-500 font-medium">
                            Line
                          </th>
                          <th className="px-3 sm:px-4 py-2 text-left text-xs text-gray-500 font-medium">
                            Category
                          </th>
                          <th className="px-3 sm:px-4 py-2 text-right text-xs text-gray-500 font-medium">
                            Amount
                          </th>
                          <th className="px-3 sm:px-4 py-2 text-right text-xs text-gray-500 font-medium hidden sm:table-cell">
                            Count
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        {SCHEDULE_E_LINES.filter(
                          ([num]) => categoryTotals[num]
                        ).map(([num, name]) => {
                          const val = categoryTotals[num];
                          const count = transactions.filter(
                            (t) => getCatLine(t.category) === num
                          ).length;
                          const cClass =
                            CAT_COLORS[num] || CAT_COLORS['19'];
                          return (
                            <tr
                              key={num}
                              className="border-b border-gray-800/50 hover:bg-gray-800/30"
                            >
                              <td className="px-3 sm:px-4 py-2 text-gray-500 font-mono text-xs">
                                {num}
                              </td>
                              <td className="px-3 sm:px-4 py-2">
                                <span
                                  className={`text-[10px] sm:text-xs font-medium px-2 py-0.5 rounded-full ${cClass}`}
                                >
                                  {name}
                                </span>
                              </td>
                              <td
                                className={`px-3 sm:px-4 py-2 text-right font-mono tabular-nums ${
                                  val > 0
                                    ? 'text-emerald-400'
                                    : 'text-red-400'
                                }`}
                              >
                                {fmt(val)}
                              </td>
                              <td className="px-3 sm:px-4 py-2 text-right text-gray-600 text-xs hidden sm:table-cell">
                                {count}
                              </td>
                            </tr>
                          );
                        })}
                        <tr className="bg-gray-800/50">
                          <td className="px-3 sm:px-4 py-3"></td>
                          <td className="px-3 sm:px-4 py-3 font-bold text-white text-xs sm:text-sm">
                            NET INCOME
                          </td>
                          <td
                            className={`px-3 sm:px-4 py-3 text-right font-mono font-bold tabular-nums ${
                              totalIncome + totalExpenses >= 0
                                ? 'text-emerald-400'
                                : 'text-red-400'
                            }`}
                          >
                            {fmt(totalIncome + totalExpenses)}
                          </td>
                          <td className="px-3 sm:px-4 py-3 text-right text-gray-600 text-xs hidden sm:table-cell">
                            {transactions.length}
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            )}
          </>
        )}
      </main>
    </div>
  );
}

// ── Saved Reports + Annual Consolidation ────────────────────────────────────

function SavedReportsSection({
  onLoad,
  onConsolidate,
}: {
  onLoad: (r: SavedReport) => void;
  onConsolidate: (ids: string[]) => void;
}) {
  const [reports, setReports] = useState<SavedReport[]>([]);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [consolidateMode, setConsolidateMode] = useState(false);

  useEffect(() => {
    setReports(getReports());
  }, []);

  const handleDelete = (id: string) => {
    if (window.confirm('Delete this saved report?')) {
      deleteReport(id);
      setReports((prev) => prev.filter((r) => r.id !== id));
      setSelectedIds((prev) => {
        const next = new Set(prev);
        next.delete(id);
        return next;
      });
    }
  };

  const toggleSelect = (id: string) => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  if (reports.length === 0) return null;

  return (
    <div className="mt-6">
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-sm font-semibold text-gray-500">Saved Reports</h3>
        <div className="flex gap-2">
          {consolidateMode && selectedIds.size >= 2 && (
            <button
              onClick={() => onConsolidate(Array.from(selectedIds))}
              className="text-[11px] sm:text-xs px-3 py-1 rounded-lg bg-emerald-600 text-white hover:bg-emerald-500"
            >
              Combine {selectedIds.size} Reports
            </button>
          )}
          <button
            onClick={() => {
              setConsolidateMode(!consolidateMode);
              setSelectedIds(new Set());
            }}
            className={`text-[11px] sm:text-xs px-3 py-1 rounded-lg border transition-colors ${
              consolidateMode
                ? 'border-emerald-600 text-emerald-400'
                : 'border-gray-700 text-gray-500 hover:text-gray-300'
            }`}
          >
            {consolidateMode ? 'Cancel' : 'Combine for Year'}
          </button>
        </div>
      </div>

      {consolidateMode && (
        <p className="text-xs text-gray-600 mb-2">
          Select 2 or more monthly reports to combine into an annual Schedule E.
        </p>
      )}

      <div className="grid gap-2 grid-cols-1 sm:grid-cols-2">
        {reports.map((r) => (
          <div
            key={r.id}
            className={`bg-gray-900 border rounded-lg p-3 text-left transition-colors relative group ${
              consolidateMode && selectedIds.has(r.id)
                ? 'border-emerald-500 bg-emerald-950/20'
                : 'border-gray-800 hover:border-gray-600'
            }`}
          >
            <button
              onClick={() =>
                consolidateMode ? toggleSelect(r.id) : onLoad(r)
              }
              className="w-full text-left"
            >
              <div className="flex items-start justify-between">
                <div>
                  <p className="font-medium text-sm text-gray-300">
                    {r.label}
                  </p>
                  <p className="text-xs text-gray-600">
                    {r.transactions.length} transactions &middot;{' '}
                    {new Date(r.savedAt).toLocaleDateString()}
                  </p>
                </div>
                {consolidateMode && (
                  <div
                    className={`w-5 h-5 rounded border-2 flex items-center justify-center shrink-0 mt-0.5 ${
                      selectedIds.has(r.id)
                        ? 'border-emerald-500 bg-emerald-500 text-white'
                        : 'border-gray-600'
                    }`}
                  >
                    {selectedIds.has(r.id) && (
                      <span className="text-xs">&#10003;</span>
                    )}
                  </div>
                )}
              </div>
            </button>
            {!consolidateMode && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  handleDelete(r.id);
                }}
                className="absolute top-2 right-2 text-gray-700 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity text-sm"
                title="Delete report"
              >
                &times;
              </button>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
